In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('sample_.dat', skiprows=30, usecols=[2,3,4]) #.dat、上３０行無視、２、３、４列インプット
x = np.array(df)
m = x[:, 2].reshape(-1, 55) #行：温度、　列：磁場
H = x[0:55, 0] #磁場（データ）
T = np.arange(10, 60, 10) #温度（生成）

dS_all = np.empty((0, 4)) #dM/dTbox, columns:磁場
for i in range(H.size):
    if i==0:
        dH = 0
    else:
        dH = (H[i]-H[i-1])
    dS = np.empty(0) #dM/dTbox初期化, columns:磁場
    for j in range(T.size-1):
        #T[j+1]-T[j]
        y = (m[j+1, i]-m[j, i])*dH/10
        dS = np.append(dS, y)
    dS_all = np.append(dS_all, [dS], axis=0)
print(dS_all)
S = np.sum(dS_all, axis=0)
print(S)
T = np.arange(10, 50, 10) #温度（生成）
ST = np.stack([T, S], 1)
f = pd.DataFrame(ST, columns=['T', 'S'])
f.to_csv('ST.csv', index=False)

[[-0.000000e+00 -0.000000e+00 -0.000000e+00  0.000000e+00]
 [-2.319100e-03 -2.465400e-03 -2.243920e-03  2.187800e-03]
 [-4.234740e-03 -4.119840e-03 -3.181960e-03  1.011360e-03]
 [-6.053900e-03 -5.955360e-03 -3.951780e-03  2.968000e-04]
 [-6.265340e-03 -4.956020e-03 -3.533340e-03 -1.019500e-03]
 [-9.059200e-03 -8.007200e-03 -6.193200e-03 -3.078200e-03]
 [-1.105920e-02 -1.040140e-02 -6.818800e-03 -4.048200e-03]
 [-1.331520e-02 -1.146840e-02 -8.485600e-03 -4.948200e-03]
 [-1.476760e-02 -1.308860e-02 -9.773800e-03 -4.964000e-03]
 [-1.582480e-02 -1.466840e-02 -1.067680e-02 -5.748600e-03]
 [-1.823040e-02 -1.618540e-02 -1.151640e-02 -6.851000e-03]
 [-1.964980e-02 -1.785040e-02 -1.233580e-02 -7.860800e-03]
 [-2.098120e-02 -1.893580e-02 -1.431700e-02 -7.668600e-03]
 [-2.260880e-02 -2.027660e-02 -1.482920e-02 -9.307200e-03]
 [-2.437860e-02 -2.127380e-02 -1.611600e-02 -1.032720e-02]
 [-2.540720e-02 -2.299660e-02 -1.750120e-02 -1.169520e-02]
 [-2.681880e-02 -2.438180e-02 -1.902880e-02 -1.304480e-0